package com.bm.student_manager.entity;

public class Classa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.UUID
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.class_type
     *
     * @mbg.generated
     */
    private String classType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.teacher_id
     *
     * @mbg.generated
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.teacher_name
     *
     * @mbg.generated
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.start_class_time
     *
     * @mbg.generated
     */
    private String startClassTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.end_class_time
     *
     * @mbg.generated
     */
    private String endClassTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.expect_number_people
     *
     * @mbg.generated
     */
    private String expectNumberPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.actual_number_people
     *
     * @mbg.generated
     */
    private String actualNumberPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.plan_number
     *
     * @mbg.generated
     */
    private String planNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.already_number
     *
     * @mbg.generated
     */
    private String alreadyNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classa.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.UUID
     *
     * @return the value of classa.UUID
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.UUID
     *
     * @param uuid the value for classa.UUID
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.class_type
     *
     * @return the value of classa.class_type
     *
     * @mbg.generated
     */
    public String getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.class_type
     *
     * @param classType the value for classa.class_type
     *
     * @mbg.generated
     */
    public void setClassType(String classType) {
        this.classType = classType == null ? null : classType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.class_name
     *
     * @return the value of classa.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.class_name
     *
     * @param className the value for classa.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.teacher_id
     *
     * @return the value of classa.teacher_id
     *
     * @mbg.generated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.teacher_id
     *
     * @param teacherId the value for classa.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.teacher_name
     *
     * @return the value of classa.teacher_name
     *
     * @mbg.generated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.teacher_name
     *
     * @param teacherName the value for classa.teacher_name
     *
     * @mbg.generated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.phone
     *
     * @return the value of classa.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.phone
     *
     * @param phone the value for classa.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.start_class_time
     *
     * @return the value of classa.start_class_time
     *
     * @mbg.generated
     */
    public String getStartClassTime() {
        return startClassTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.start_class_time
     *
     * @param startClassTime the value for classa.start_class_time
     *
     * @mbg.generated
     */
    public void setStartClassTime(String startClassTime) {
        this.startClassTime = startClassTime == null ? null : startClassTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.end_class_time
     *
     * @return the value of classa.end_class_time
     *
     * @mbg.generated
     */
    public String getEndClassTime() {
        return endClassTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.end_class_time
     *
     * @param endClassTime the value for classa.end_class_time
     *
     * @mbg.generated
     */
    public void setEndClassTime(String endClassTime) {
        this.endClassTime = endClassTime == null ? null : endClassTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.expect_number_people
     *
     * @return the value of classa.expect_number_people
     *
     * @mbg.generated
     */
    public String getExpectNumberPeople() {
        return expectNumberPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.expect_number_people
     *
     * @param expectNumberPeople the value for classa.expect_number_people
     *
     * @mbg.generated
     */
    public void setExpectNumberPeople(String expectNumberPeople) {
        this.expectNumberPeople = expectNumberPeople == null ? null : expectNumberPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.actual_number_people
     *
     * @return the value of classa.actual_number_people
     *
     * @mbg.generated
     */
    public String getActualNumberPeople() {
        return actualNumberPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.actual_number_people
     *
     * @param actualNumberPeople the value for classa.actual_number_people
     *
     * @mbg.generated
     */
    public void setActualNumberPeople(String actualNumberPeople) {
        this.actualNumberPeople = actualNumberPeople == null ? null : actualNumberPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.plan_number
     *
     * @return the value of classa.plan_number
     *
     * @mbg.generated
     */
    public String getPlanNumber() {
        return planNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.plan_number
     *
     * @param planNumber the value for classa.plan_number
     *
     * @mbg.generated
     */
    public void setPlanNumber(String planNumber) {
        this.planNumber = planNumber == null ? null : planNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.already_number
     *
     * @return the value of classa.already_number
     *
     * @mbg.generated
     */
    public String getAlreadyNumber() {
        return alreadyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.already_number
     *
     * @param alreadyNumber the value for classa.already_number
     *
     * @mbg.generated
     */
    public void setAlreadyNumber(String alreadyNumber) {
        this.alreadyNumber = alreadyNumber == null ? null : alreadyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.course_id
     *
     * @return the value of classa.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.course_id
     *
     * @param courseId the value for classa.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.course_name
     *
     * @return the value of classa.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.course_name
     *
     * @param courseName the value for classa.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classa.remarks
     *
     * @return the value of classa.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classa.remarks
     *
     * @param remarks the value for classa.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}