package com.bm.student_manager.entity;

public class ClassScheduleCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.UUID
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.teacher_id
     *
     * @mbg.generated
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.teacher_name
     *
     * @mbg.generated
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.course_type
     *
     * @mbg.generated
     */
    private String courseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.start_time
     *
     * @mbg.generated
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.end_time
     *
     * @mbg.generated
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.WEEK
     *
     * @mbg.generated
     */
    private String week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule_card.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.UUID
     *
     * @return the value of class_schedule_card.UUID
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.UUID
     *
     * @param uuid the value for class_schedule_card.UUID
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.course_id
     *
     * @return the value of class_schedule_card.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.course_id
     *
     * @param courseId the value for class_schedule_card.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.teacher_id
     *
     * @return the value of class_schedule_card.teacher_id
     *
     * @mbg.generated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.teacher_id
     *
     * @param teacherId the value for class_schedule_card.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.teacher_name
     *
     * @return the value of class_schedule_card.teacher_name
     *
     * @mbg.generated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.teacher_name
     *
     * @param teacherName the value for class_schedule_card.teacher_name
     *
     * @mbg.generated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.course_type
     *
     * @return the value of class_schedule_card.course_type
     *
     * @mbg.generated
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.course_type
     *
     * @param courseType the value for class_schedule_card.course_type
     *
     * @mbg.generated
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType == null ? null : courseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.course_name
     *
     * @return the value of class_schedule_card.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.course_name
     *
     * @param courseName the value for class_schedule_card.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.start_time
     *
     * @return the value of class_schedule_card.start_time
     *
     * @mbg.generated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.start_time
     *
     * @param startTime the value for class_schedule_card.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.end_time
     *
     * @return the value of class_schedule_card.end_time
     *
     * @mbg.generated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.end_time
     *
     * @param endTime the value for class_schedule_card.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.WEEK
     *
     * @return the value of class_schedule_card.WEEK
     *
     * @mbg.generated
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.WEEK
     *
     * @param week the value for class_schedule_card.WEEK
     *
     * @mbg.generated
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.STATUS
     *
     * @return the value of class_schedule_card.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.STATUS
     *
     * @param status the value for class_schedule_card.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule_card.remarks
     *
     * @return the value of class_schedule_card.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule_card.remarks
     *
     * @param remarks the value for class_schedule_card.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}