package com.bm.student_manager.entity;

public class Satisfaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column satisfaction.UUID
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column satisfaction.TIME
     *
     * @mbg.generated
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column satisfaction.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column satisfaction.investigator
     *
     * @mbg.generated
     */
    private String investigator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column satisfaction.respondents
     *
     * @mbg.generated
     */
    private String respondents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column satisfaction.survey_satisfaction
     *
     * @mbg.generated
     */
    private String surveySatisfaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column satisfaction.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column satisfaction.UUID
     *
     * @return the value of satisfaction.UUID
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column satisfaction.UUID
     *
     * @param uuid the value for satisfaction.UUID
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column satisfaction.TIME
     *
     * @return the value of satisfaction.TIME
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column satisfaction.TIME
     *
     * @param time the value for satisfaction.TIME
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column satisfaction.content
     *
     * @return the value of satisfaction.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column satisfaction.content
     *
     * @param content the value for satisfaction.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column satisfaction.investigator
     *
     * @return the value of satisfaction.investigator
     *
     * @mbg.generated
     */
    public String getInvestigator() {
        return investigator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column satisfaction.investigator
     *
     * @param investigator the value for satisfaction.investigator
     *
     * @mbg.generated
     */
    public void setInvestigator(String investigator) {
        this.investigator = investigator == null ? null : investigator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column satisfaction.respondents
     *
     * @return the value of satisfaction.respondents
     *
     * @mbg.generated
     */
    public String getRespondents() {
        return respondents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column satisfaction.respondents
     *
     * @param respondents the value for satisfaction.respondents
     *
     * @mbg.generated
     */
    public void setRespondents(String respondents) {
        this.respondents = respondents == null ? null : respondents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column satisfaction.survey_satisfaction
     *
     * @return the value of satisfaction.survey_satisfaction
     *
     * @mbg.generated
     */
    public String getSurveySatisfaction() {
        return surveySatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column satisfaction.survey_satisfaction
     *
     * @param surveySatisfaction the value for satisfaction.survey_satisfaction
     *
     * @mbg.generated
     */
    public void setSurveySatisfaction(String surveySatisfaction) {
        this.surveySatisfaction = surveySatisfaction == null ? null : surveySatisfaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column satisfaction.remarks
     *
     * @return the value of satisfaction.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column satisfaction.remarks
     *
     * @param remarks the value for satisfaction.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}