package com.bm.student_manager.entity;

public class StudentCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_check.UUID
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_check.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_check.student_name
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_check.sourse_id
     *
     * @mbg.generated
     */
    private String sourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_check.course_name_s_e_time
     *
     * @mbg.generated
     */
    private String courseNameSETime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_check.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_check.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_check.UUID
     *
     * @return the value of student_check.UUID
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_check.UUID
     *
     * @param uuid the value for student_check.UUID
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_check.student_id
     *
     * @return the value of student_check.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_check.student_id
     *
     * @param studentId the value for student_check.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_check.student_name
     *
     * @return the value of student_check.student_name
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_check.student_name
     *
     * @param studentName the value for student_check.student_name
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_check.sourse_id
     *
     * @return the value of student_check.sourse_id
     *
     * @mbg.generated
     */
    public String getSourseId() {
        return sourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_check.sourse_id
     *
     * @param sourseId the value for student_check.sourse_id
     *
     * @mbg.generated
     */
    public void setSourseId(String sourseId) {
        this.sourseId = sourseId == null ? null : sourseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_check.course_name_s_e_time
     *
     * @return the value of student_check.course_name_s_e_time
     *
     * @mbg.generated
     */
    public String getCourseNameSETime() {
        return courseNameSETime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_check.course_name_s_e_time
     *
     * @param courseNameSETime the value for student_check.course_name_s_e_time
     *
     * @mbg.generated
     */
    public void setCourseNameSETime(String courseNameSETime) {
        this.courseNameSETime = courseNameSETime == null ? null : courseNameSETime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_check.STATUS
     *
     * @return the value of student_check.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_check.STATUS
     *
     * @param status the value for student_check.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_check.remarks
     *
     * @return the value of student_check.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_check.remarks
     *
     * @param remarks the value for student_check.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}