package com.bm.student_manager.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classs
     *
     * @mbg.generated
     */
    private String classs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.parents_name
     *
     * @mbg.generated
     */
    private String parentsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.parents_number
     *
     * @mbg.generated
     */
    private String parentsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.number
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sentrancedate
     *
     * @mbg.generated
     */
    private String sentrancedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.admissions_teacher
     *
     * @mbg.generated
     */
    private String admissionsTeacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.classs
     *
     * @return the value of student.classs
     *
     * @mbg.generated
     */
    public String getClasss() {
        return classs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.classs
     *
     * @param classs the value for student.classs
     *
     * @mbg.generated
     */
    public void setClasss(String classs) {
        this.classs = classs == null ? null : classs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.NAME
     *
     * @return the value of student.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.NAME
     *
     * @param name the value for student.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birthday
     *
     * @return the value of student.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birthday
     *
     * @param birthday the value for student.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.PASSWORD
     *
     * @return the value of student.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.PASSWORD
     *
     * @param password the value for student.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.parents_name
     *
     * @return the value of student.parents_name
     *
     * @mbg.generated
     */
    public String getParentsName() {
        return parentsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.parents_name
     *
     * @param parentsName the value for student.parents_name
     *
     * @mbg.generated
     */
    public void setParentsName(String parentsName) {
        this.parentsName = parentsName == null ? null : parentsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.parents_number
     *
     * @return the value of student.parents_number
     *
     * @mbg.generated
     */
    public String getParentsNumber() {
        return parentsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.parents_number
     *
     * @param parentsNumber the value for student.parents_number
     *
     * @mbg.generated
     */
    public void setParentsNumber(String parentsNumber) {
        this.parentsNumber = parentsNumber == null ? null : parentsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.number
     *
     * @return the value of student.number
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.number
     *
     * @param number the value for student.number
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sentrancedate
     *
     * @return the value of student.sentrancedate
     *
     * @mbg.generated
     */
    public String getSentrancedate() {
        return sentrancedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sentrancedate
     *
     * @param sentrancedate the value for student.sentrancedate
     *
     * @mbg.generated
     */
    public void setSentrancedate(String sentrancedate) {
        this.sentrancedate = sentrancedate == null ? null : sentrancedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.state
     *
     * @return the value of student.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.state
     *
     * @param state the value for student.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.admissions_teacher
     *
     * @return the value of student.admissions_teacher
     *
     * @mbg.generated
     */
    public String getAdmissionsTeacher() {
        return admissionsTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.admissions_teacher
     *
     * @param admissionsTeacher the value for student.admissions_teacher
     *
     * @mbg.generated
     */
    public void setAdmissionsTeacher(String admissionsTeacher) {
        this.admissionsTeacher = admissionsTeacher == null ? null : admissionsTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.remarks
     *
     * @return the value of student.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.remarks
     *
     * @param remarks the value for student.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}